// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/hello-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product_Price_Unit int32

const (
	Product_Price_USD Product_Price_Unit = 0
	Product_Price_CNY Product_Price_Unit = 1
	Product_Price_YEN Product_Price_Unit = 2
)

var Product_Price_Unit_name = map[int32]string{
	0: "USD",
	1: "CNY",
	2: "YEN",
}

var Product_Price_Unit_value = map[string]int32{
	"USD": 0,
	"CNY": 1,
	"YEN": 2,
}

func (x Product_Price_Unit) String() string {
	return proto.EnumName(Product_Price_Unit_name, int32(x))
}

func (Product_Price_Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c496708e7f71e5c, []int{0, 0, 0}
}

type Product struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                *Product_Price `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c496708e7f71e5c, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetPrice() *Product_Price {
	if m != nil {
		return m.Price
	}
	return nil
}

type Product_Price struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Unit                 Product_Price_Unit   `protobuf:"varint,5,opt,name=unit,proto3,enum=v1.Product_Price_Unit" json:"unit,omitempty"`
	Number               float64              `protobuf:"fixed64,2,opt,name=number,proto3" json:"number,omitempty"`
	UploadedAt           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Product_Price) Reset()         { *m = Product_Price{} }
func (m *Product_Price) String() string { return proto.CompactTextString(m) }
func (*Product_Price) ProtoMessage()    {}
func (*Product_Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c496708e7f71e5c, []int{0, 0}
}

func (m *Product_Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product_Price.Unmarshal(m, b)
}
func (m *Product_Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product_Price.Marshal(b, m, deterministic)
}
func (m *Product_Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product_Price.Merge(m, src)
}
func (m *Product_Price) XXX_Size() int {
	return xxx_messageInfo_Product_Price.Size(m)
}
func (m *Product_Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Product_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Product_Price proto.InternalMessageInfo

func (m *Product_Price) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product_Price) GetUnit() Product_Price_Unit {
	if m != nil {
		return m.Unit
	}
	return Product_Price_USD
}

func (m *Product_Price) GetNumber() float64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Product_Price) GetUploadedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UploadedAt
	}
	return nil
}

func (m *Product_Price) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Products struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Products) Reset()         { *m = Products{} }
func (m *Products) String() string { return proto.CompactTextString(m) }
func (*Products) ProtoMessage()    {}
func (*Products) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c496708e7f71e5c, []int{1}
}

func (m *Products) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Products.Unmarshal(m, b)
}
func (m *Products) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Products.Marshal(b, m, deterministic)
}
func (m *Products) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Products.Merge(m, src)
}
func (m *Products) XXX_Size() int {
	return xxx_messageInfo_Products.Size(m)
}
func (m *Products) XXX_DiscardUnknown() {
	xxx_messageInfo_Products.DiscardUnknown(m)
}

var xxx_messageInfo_Products proto.InternalMessageInfo

func (m *Products) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type ProductRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Product              *Product `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductRequest) Reset()         { *m = ProductRequest{} }
func (m *ProductRequest) String() string { return proto.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()    {}
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c496708e7f71e5c, []int{2}
}

func (m *ProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductRequest.Unmarshal(m, b)
}
func (m *ProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductRequest.Marshal(b, m, deterministic)
}
func (m *ProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductRequest.Merge(m, src)
}
func (m *ProductRequest) XXX_Size() int {
	return xxx_messageInfo_ProductRequest.Size(m)
}
func (m *ProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductRequest proto.InternalMessageInfo

func (m *ProductRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type ProductResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductResponse) Reset()         { *m = ProductResponse{} }
func (m *ProductResponse) String() string { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()    {}
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c496708e7f71e5c, []int{3}
}

func (m *ProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponse.Unmarshal(m, b)
}
func (m *ProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponse.Marshal(b, m, deterministic)
}
func (m *ProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponse.Merge(m, src)
}
func (m *ProductResponse) XXX_Size() int {
	return xxx_messageInfo_ProductResponse.Size(m)
}
func (m *ProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponse proto.InternalMessageInfo

func (m *ProductResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ProductResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("v1.Product_Price_Unit", Product_Price_Unit_name, Product_Price_Unit_value)
	proto.RegisterType((*Product)(nil), "v1.Product")
	proto.RegisterType((*Product_Price)(nil), "v1.Product.Price")
	proto.RegisterType((*Products)(nil), "v1.Products")
	proto.RegisterType((*ProductRequest)(nil), "v1.ProductRequest")
	proto.RegisterType((*ProductResponse)(nil), "v1.ProductResponse")
}

func init() { proto.RegisterFile("v1/hello-service.proto", fileDescriptor_4c496708e7f71e5c) }

var fileDescriptor_4c496708e7f71e5c = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x4d, 0xd2, 0x6e, 0xb7, 0xa7, 0xdb, 0x3f, 0x1e, 0xb5, 0xc4, 0xb0, 0xb0, 0x35, 0x20,
	0x5b, 0x0a, 0x26, 0xb4, 0xbd, 0x52, 0xaf, 0xca, 0x56, 0x50, 0x90, 0x75, 0xc9, 0x5a, 0xa1, 0x57,
	0x32, 0x6d, 0xc6, 0x3a, 0x90, 0x66, 0x62, 0x32, 0xc9, 0x8d, 0x78, 0xe3, 0x2b, 0xf8, 0x0e, 0xbe,
	0x86, 0x0f, 0xe1, 0x2b, 0xf8, 0x14, 0x5e, 0x49, 0x66, 0x26, 0xa5, 0x8b, 0x45, 0xd1, 0xbb, 0x93,
	0x73, 0xbe, 0xfc, 0xe6, 0x7c, 0xe7, 0x1c, 0xe8, 0x17, 0x63, 0xff, 0x3d, 0x8d, 0x22, 0xfe, 0x28,
	0xa3, 0x69, 0xc1, 0xd6, 0xd4, 0x4b, 0x52, 0x2e, 0x38, 0x9a, 0xc5, 0xd8, 0x39, 0xdb, 0x70, 0xbe,
	0x89, 0xa8, 0x2f, 0x33, 0xab, 0xfc, 0x9d, 0x2f, 0xd8, 0x96, 0x66, 0x82, 0x6c, 0x13, 0x25, 0x72,
	0x4e, 0xb5, 0x80, 0x24, 0xcc, 0x27, 0x71, 0xcc, 0x05, 0x11, 0x8c, 0xc7, 0x99, 0xaa, 0xba, 0xdf,
	0x4c, 0x68, 0x5c, 0xa5, 0x3c, 0xcc, 0xd7, 0x02, 0x3b, 0x60, 0xb2, 0xd0, 0x36, 0x06, 0xc6, 0xd0,
	0x0a, 0x4c, 0x16, 0xe2, 0x39, 0xd4, 0x93, 0x94, 0xad, 0xa9, 0x6d, 0x0e, 0x8c, 0x61, 0x6b, 0x72,
	0xdb, 0x2b, 0xc6, 0x9e, 0xd6, 0x7a, 0x57, 0x65, 0x21, 0x50, 0x75, 0xe7, 0xa7, 0x01, 0x75, 0x99,
	0x40, 0x84, 0x5a, 0x4c, 0xb6, 0x54, 0x42, 0x9a, 0x81, 0x8c, 0x71, 0x04, 0xb5, 0x3c, 0x66, 0xc2,
	0xae, 0x0f, 0x8c, 0x61, 0x67, 0xd2, 0xff, 0x8d, 0xe2, 0x2d, 0x62, 0x26, 0x02, 0xa9, 0xc1, 0x3e,
	0x1c, 0xc5, 0xf9, 0x76, 0x45, 0x53, 0xf9, 0xa6, 0x11, 0xe8, 0x2f, 0x7c, 0x0a, 0xad, 0x3c, 0x89,
	0x38, 0x09, 0x69, 0xf8, 0x96, 0x08, 0xdb, 0x92, 0x0d, 0x39, 0x9e, 0xb2, 0xe6, 0x55, 0xde, 0xbd,
	0xd7, 0x95, 0xf7, 0x00, 0x2a, 0xf9, 0x4c, 0xe0, 0x63, 0x80, 0x3c, 0x09, 0x89, 0x50, 0xff, 0xd6,
	0xfe, 0xfa, 0x6f, 0x53, 0xab, 0x67, 0xc2, 0x7d, 0x00, 0xb5, 0xb2, 0x3b, 0x6c, 0x80, 0xb5, 0xb8,
	0x9e, 0xf7, 0x6e, 0x95, 0xc1, 0xc5, 0xe5, 0xb2, 0x67, 0x94, 0xc1, 0xf2, 0xd9, 0x65, 0xcf, 0x74,
	0xa7, 0x70, 0xac, 0xed, 0x64, 0x78, 0x0e, 0xc7, 0x89, 0x8e, 0x6d, 0x63, 0x60, 0x0d, 0x5b, 0x93,
	0xd6, 0x9e, 0xdd, 0x60, 0x57, 0x74, 0x5f, 0x40, 0xa7, 0x4a, 0xd2, 0x0f, 0x39, 0xcd, 0x04, 0xf6,
	0xc0, 0x22, 0x09, 0xd3, 0x83, 0x2b, 0x43, 0x7c, 0x08, 0x0d, 0xad, 0xd7, 0x0b, 0xb8, 0xc1, 0xaa,
	0x6a, 0xee, 0x14, 0xba, 0x3b, 0x54, 0x96, 0xf0, 0x38, 0xa3, 0x07, 0x58, 0x6a, 0xb5, 0x66, 0xb5,
	0xda, 0xc9, 0x57, 0x0b, 0x4e, 0x9e, 0x97, 0x17, 0x75, 0xad, 0x0e, 0x0a, 0x5f, 0x41, 0xfb, 0x22,
	0xa5, 0x44, 0xd0, 0xea, 0x18, 0x70, 0xff, 0x31, 0xd5, 0xa3, 0x73, 0xe7, 0x46, 0x4e, 0x3d, 0xe6,
	0xde, 0xfb, 0xfc, 0xfd, 0xc7, 0x17, 0xb3, 0xeb, 0x82, 0x5f, 0x8c, 0xfd, 0xb5, 0x64, 0x3c, 0x31,
	0x46, 0x38, 0x87, 0x6e, 0x40, 0x49, 0x38, 0x8b, 0xa2, 0xdd, 0x74, 0x0e, 0x21, 0x4f, 0xf6, 0x72,
	0x99, 0xdb, 0x95, 0xac, 0x26, 0x36, 0x4a, 0xd6, 0x86, 0x0a, 0x7c, 0x09, 0xad, 0x92, 0xf2, 0xa7,
	0xa6, 0xf6, 0xa7, 0xe2, 0x9e, 0x4a, 0x40, 0x1f, 0xef, 0x6a, 0x80, 0xff, 0x51, 0x8f, 0xc9, 0x63,
	0xe1, 0x27, 0x5c, 0x42, 0x7b, 0x21, 0x57, 0xfb, 0xcf, 0x26, 0xcf, 0x24, 0xf7, 0xbe, 0x73, 0x90,
	0x5b, 0xda, 0x7d, 0x03, 0xed, 0x39, 0x8d, 0xe8, 0x7f, 0xa0, 0x75, 0xcb, 0xa3, 0x83, 0xe8, 0xd5,
	0x91, 0xbc, 0xcf, 0xe9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xe0, 0xda, 0x3f, 0x03, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	CreateProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	ReadAllProducts(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*Products, error)
	ReadProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*Product, error)
	UpdateProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	DeleteProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) CreateProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/v1.HelloService/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) ReadAllProducts(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*Products, error) {
	out := new(Products)
	err := c.cc.Invoke(ctx, "/v1.HelloService/ReadAllProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) ReadProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/v1.HelloService/ReadProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) UpdateProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/v1.HelloService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) DeleteProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/v1.HelloService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	CreateProduct(context.Context, *ProductRequest) (*ProductResponse, error)
	ReadAllProducts(context.Context, *ProductRequest) (*Products, error)
	ReadProduct(context.Context, *ProductRequest) (*Product, error)
	UpdateProduct(context.Context, *ProductRequest) (*ProductResponse, error)
	DeleteProduct(context.Context, *ProductRequest) (*ProductResponse, error)
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) CreateProduct(ctx context.Context, req *ProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (*UnimplementedHelloServiceServer) ReadAllProducts(ctx context.Context, req *ProductRequest) (*Products, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAllProducts not implemented")
}
func (*UnimplementedHelloServiceServer) ReadProduct(ctx context.Context, req *ProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadProduct not implemented")
}
func (*UnimplementedHelloServiceServer) UpdateProduct(ctx context.Context, req *ProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedHelloServiceServer) DeleteProduct(ctx context.Context, req *ProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.HelloService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).CreateProduct(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_ReadAllProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).ReadAllProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.HelloService/ReadAllProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).ReadAllProducts(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_ReadProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).ReadProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.HelloService/ReadProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).ReadProduct(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.HelloService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).UpdateProduct(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.HelloService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).DeleteProduct(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _HelloService_CreateProduct_Handler,
		},
		{
			MethodName: "ReadAllProducts",
			Handler:    _HelloService_ReadAllProducts_Handler,
		},
		{
			MethodName: "ReadProduct",
			Handler:    _HelloService_ReadProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _HelloService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _HelloService_DeleteProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/hello-service.proto",
}
